version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: 'hydra'
      ADMINER_DEFAULT_SERVER: 'postgresql'
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PSSWD}
      POSTGRES_DB: ${DB}
    volumes:
      - ./initialization-scripts:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
