version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: 'dracula'
    ports:
      - 8080:8080

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 'root'
      MARIADB_DATABASE : 'nix'
    volumes:
      - ./initialization-scripts:/docker-entrypoint-initdb.d:ro