version: '2.4'

services:

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: 'hydra'
      ADMINER_DEFAULT_SERVER: 'postgresql'
    ports:
      - 8080:8080
    networks:
        BridgeServer:
            ipv4_address: ${IP_AD}


  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PSSWD}
      POSTGRES_DB: ${DB}
    volumes:
      - ./initialization-scripts:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
        BridgeServer:
            ipv4_address: ${IP_POST}


##################################
#
# - You can delete the part below for your usecase 
# - And the networks in the 
#
##################################


networks:
    BridgeServer:
        name: ${NETWORK}
        driver: ${DRIVER}
        driver_opts: 
            parent: ${PARENT}
        ipam:
            config:
                - subnet: ${SUBNET}
                  gateway: ${GATEWAY}
